version: '3.5'

services:
    database:
        build:
            context: docker/db
        image: db-mf
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_USER=test
            - MYSQL_PASSWORD=1234
            - MYSQL_ROOT_PASSWORD=docker
        container_name: database
        ports:
            - "3301:3306"

    php-fpm:
        build:
            context: docker/php
        image: php-fpm-mf
        networks:
            - backend
        depends_on:
            - database
        environment:
            - APP_ENV=$${APP_ENV}
            - APP_SECRET=$${APP_SECRET}
            - DATABASE_URL=mysql://$${DATABASE_USER}:$${DATABASE_PASSWORD}@database:3306/$${DATABASE_NAME}?10.5.8-MariaDB-1:10.5.8+maria~focal
        volumes:
            - ./app:/app
            - ./logs:/var/log/nginx
            - ./logs/xdebug:/var/log/xdebug
            - ./docker/php/:/usr/local/etc/php
            - ./docker/php/ini/custom.ini:/usr/local/etc/php/conf.d/
        container_name: web
        ports:
            - "9000:9000"

    nginx:
        build:
            context: docker/nginx
        image: nginx-mf
        networks:
            - backend
        volumes:
            -  ./app:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - ./docker/nginx/:/usr/local/etc/php

        depends_on:
            - php-fpm
        ports:
            - "8090:80"
        container_name: server

#    redis:
#        build:
##            context: docker/redis
#        image: redis-mf
#        networks:
#             - backend
#        container_name: redis
#        privileged: true
#        command: sh -c "./init.sh"
#        volumes:
#            - ./redisData:/data
#        ports:
#            - "6379:6379"
networks:
    backend:
        name: backend
